config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, path: '', as: '' do
    resources :users, only: [ :new, :create ], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [ :new, :create, :destroy ], path: '/login', path_names: { new: '/' }
  end

  resources :favorites, only: [ :index, :create, :destroy ], param: :product_id
  resources :users, only: :show, path: '/user', param: :username   # Con el path: '/user' se cambia de plural a singular
  resources :categories, except: :show
  resources :products, path: '/'

  
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  include Favoritable

  has_one_attached  :photo

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  belongs_to :category
  belongs_to :user, default: -> { Current.user }

  def owner?
    user_id == Current.user&.id
  end
  
  pg_search_scope :search_full_text, against: [
    [:title, 'A'],  # Field and priority
    [:description, 'B']
  ]

  ORDER_BY = {
    newest: "created_at DESC",
    expensive: "price DESC",
    cheapest: "price ASC"
  }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController 
  skip_before_action :protect_pages, only: [:index, :show]

  def index
    @categories = Category.order(name: :asc).load_async
    @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 12)
  end

  def show
    product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)  
    # @product = Current.user.products.new(product_params)    # Opción
    if @product.save
      redirect_to products_path, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end  
  end

  def edit
    authorize! product
  end

  def update
    authorize! product
    if product.update(product_params)
      redirect_to product_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! product
    product.destroy
    redirect_to products_path, notice: t('.destroyed'), status: :see_other
  end

  private
  def product_params
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end

  def product
    @product ||= Product.find params[:id]
  end

  def  product_params_index
    params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :favorites, :user_id )
  end

end

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: 'category' do %>
  <%= category.name %>
<% end %>

app/views/products/_favorite.html.erb
<div id="favorite">
  <% if product.favorite %>
    <%= link_to '💔', favorite_path(product_id: product.id), data:{
      turbo_method: :delete
    }, class:'mx-1' %>
  <% else %>
    <%= link_to '❤️', favorites_path(product_id: product.id), data:{
      turbo_method: :post
    }, class:'mx-1' %>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <div> - <%= error %></div>
  <% end %>
  <table>
    <tr>
      <td><%= form.label :title %></td>
      <td><%= form.text_field :title %></td>
    </tr>

    <tr>
      <td><%= form.label :description %></td>
      <td><%= form.text_area :description %></td>
    </tr>

    <tr>
      <td><%= form.label :price %></td>
      <td><%= form.number_field :price %></td>
    </tr>

    <tr>
      <td><%= form.label :Category %></td>
      <td><%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %></td>
    </tr>

    <tr>
      <td><%= form.label :photo %></td>
      <td><%= form.file_field :photo %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= image_tag @product.photo, width: 100 if @product.photo.attached? %></td>
    </tr>
  </table><br>

  <%= form.submit %>

<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product), class: 'product', 'data-turbo-frame': '_top' do %>
  <br><%= image_tag product.photo, width: 100 if product.photo.attached? %>
  <h2> <%= product.title %> </h2>    
  <span><%= product.price %>$</span><br><br>
<% end %>

app/views/products/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/index.html.erb
<div class="mt-3 mx-5">
  <%= turbo_frame_tag 'home' do  %>
    <div class="login-title mt-4 mx-3">
      <h1><%= t('.title') %></h1>
    </div>
    <div class="mt-3">
      <%= form_with url: products_path, method: :get do |f| %>

        <%= f.text_field :query_text, placeholder: t('.query_text'),
        onChange: 'this.form.requestSubmit()', value: params[:query_text]  %>

        <%= f.number_field :min_price, placeholder: t('.min_price'),
        onChange: 'this.form.requestSubmit()', value: params[:min_price] %>

        <%= f.number_field :max_price, placeholder: t('.max_price'),
        onChange: 'this.form.requestSubmit()', value: params[:max_price] %>

        <%= f.select :order_by, options_for_select( Product::ORDER_BY.keys.map{ |order| [t(".#{order}"), order] }, params[:order_by]),
        {}, { onChange: 'this.form.requestSubmit()' } %>

      <% end %>
    </div>
    <div class="mt-3">
      <%= link_to t('.all'), products_path %>
      <%= render partial: 'category', collection: @categories %>
    </div>
    <br>

    <%= turbo_frame_tag :products do %>
      <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products' do %>
        <%= render partial: 'product', collection: @products %>
        <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products', 
        src: pagy_url_for(@pagy, @pagy.next),
        loading: :lazy if @pagy.next %>
      <% end %>
    <% end %>

  <% end %>
</div>

app/views/products/new.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="mx-3">
  <%= link_to t('.edit'), edit_product_path(@product), class:'mx-1' if @product.owner? %>

  <%= link_to t('.delete'), product_path(@product), data:{
    turbo_method: :delete,
    turbo_confirm: t('common.confirm') 
    }, class:'mx-1' if @product.owner? %>

  <%= link_to "#{t('.view_profile')} #{@product.user.username}", user_path(@product.user.username), class:'mx-1' %>

  <%= render partial: 'favorite', locals: { product: @product } %>

</div>
<div class="mx-5">
    <br><br><%= image_tag @product.photo, width: 150 if @product.photo.attached? %>
  <div class="login-title">
    <h1 class='title'><%= @product.title %></h1>
  </div>
  <div class="mt-3">
    <p class='description'><%= @product.description %></p>

    <span class='price'><%= @product.price %>$</span><br><br>

  </div>


</div>